feat(placements): fixed height support
Automattic/newspack-ads pull request #439
Opened 2022-06-07 22:33 UTC by miguelpeixe

2022-06-10 20:56 UTC, kmwilkerson commented
> Mind that although we could consider applying that logic to also use the rendered creative to fit the height and remove potential blank spaces from the slot, this is problematic for 2 reasons:
> 
> - Refresh control can change the rendered creative and cause extra annoying CLS (during read-time)

We could restrict the refresh to only request the same size that was initially rendered. Doing so would limit earning potential, but only very slightly.

> - Lazy load options will also affect the time the creative height is known, which is likely to be the time when the slot is in the viewport

Is it possible to set min height only for those units within the viewport? I realize that may be an over-complication, but if possible it may be a few things easier.  

> Placement suppression per post

Just to confirm, toggle off a placement would remove the define slot, not just hide it, correct?

2022-06-11 03:56 UTC, yogeshbeniwal commented
> this PR also implements suppression of ads for specific placements on a page or post:

We are already implementing best practices as default after thorough discussion. Providing option to suppress individual ad unit per post may lead to more support request, also how scalable/frequent it will be for editor to configure individual ads per post.

2022-06-13 20:30 UTC, miguelpeixe commented
> We could restrict the refresh to only request the same size that was initially rendered. Doing so would limit earning potential, but only very slightly.

Good call! I was able to achieve that by using `slot.defineSizeMapping()` with a new size mapping with only the rendered creative dimension, so only creatives matching that specific initial creative size are allowed on refresh. Implemented in 19d5ae86ab4d1c7c7622211091c5b1ff1da41706

> Is it possible to set min height only for those units within the viewport? I realize that may be an over-complication, but if possible it may be a few things easier.

That worked smoothly without affecting the CLS score. With units above the header, below the header, and several others below the fold using blocks I got the same `0.084` score. In comparison:

| | AMP | Fixed height | Non-AMP without fixed height |
| --- | --- | --- | --- |
| CLS Score | 0 | 0.083 | 0.372 |

Implemented  in 23ce2d41a26e270cf38a74a6d40fcc0fd0afd5d7

> Just to confirm, toggle off a placement would remove the define slot, not just hide it, correct?

Correct, the slot never reaches javascript or any front-end at all.

Thank you for your input @kmwilkerson!

2022-06-13 20:32 UTC, miguelpeixe commented
f69c28155528d3c2b345bb77978d9197c60d5d89 implements a slight change to our "viewport" logic. We can't just consider **in** viewport. Slots rendered on the past viewport will also affect CLS and should have their height fixed. Browsers now preserve scroll depth on simple refreshes.

2022-06-13 20:35 UTC, miguelpeixe commented
> We are already implementing best practices as default after thorough discussion. Providing option to suppress individual ad unit per post may lead to more support request. Also how scalable/frequent it will be for editor to suppress individual ads per post.

@yogeshbeniwal we currently don't have any appropriate solution to prevent a blank space to appear in case a publisher wants a good CLS score and doesn't want above-the-fold ads on a specific page. Unfortunately, no front-end calculation is soon enough in the render to avoid CLS.

2022-06-14 12:40 UTC, adekbadek requested changes
Left some minor tweaks, otherwise it's working well!

Is it correct to say that an ad with the fixed height setting on will display a blank space _only_ if the impression is not filled (obviously) _and_ the slot is visible in the view port on page load?

2022-06-14 12:40 UTC, adekbadek commented on includes/providers/gam/class-gam-model.php
>  				$sizes,
Should be:

```suggestion
				$$ad_unit['sizes'],
```

2022-06-14 12:40 UTC, adekbadek commented on includes/providers/gam/class-gam-scripts.php
> +						if ( ad_unit.fixed_height && container.parentNode.style.height === 'auto' ) {
In a particular setup on a local site, if the impression was not filled, the `size` of the `event` was `null`, which caused an error to be thrown. There should be a check for `event`'s `size`:

```suggestion
						if ( ad_unit.fixed_height && container.parentNode.style.height === 'auto' && event.size ) {
```

2022-06-14 12:40 UTC, adekbadek commented on src/suppress-ads/index.js
> +		console.log( newspack_ads_suppress_ads_placements );
✂️
```suggestion
```

2022-06-14 12:51 UTC, miguelpeixe commented
> Is it correct to say that an ad with the fixed height setting on will display a blank space only if the impression is not filled (obviously) and the slot is visible in the view port on page load?

Correct!

Thank you for the review and catching those, @adekbadek 🙇

2022-06-16 13:14 UTC, adekbadek approved these changes

2022-06-16 13:18 UTC, merged