fix: handle zero in ad unit size gracefully
Automattic/newspack-ads pull request #520
Opened 2022-09-22 08:22 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes an issue with `0x0` ad unit size, which is possible to create. 

### How to test the changes in this Pull Request:

1. Create an ad unit with size of 0 by 0
2. Use it in a placement
3. On `master`, observe a PHP Warning about division by zero logged
4. Switch to this branch, observe no warning 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-09-23 20:23 UTC, miguelpeixe requested changes

2022-09-23 20:23 UTC, miguelpeixe commented on includes/providers/gam/class-gam-model.php
> +				if ( 0 == $size[0] ) {
```suggestion
				if ( 0 === $size[0] ) {
```

Is there a reason to use `==` here?

2022-09-26 08:11 UTC, adekbadek commented on includes/providers/gam/class-gam-model.php
> +				if ( 0 == $size[0] ) {
None, it's an oversight.

2022-09-26 13:35 UTC, miguelpeixe approved these changes

2022-09-26 16:01 UTC, merged