feat(gam): sync default ad units
Automattic/newspack-ads pull request #540
Opened 2022-10-25 17:16 UTC by miguelpeixe

Default GAM ad units are currently treated as a static configuration. They are available for usage but are not located in any database or synced to GAM.

This PR implements GAM synchronization if possible. In case a GAM connection is not available, the default static behavior is preserved.

Closes #454

### How to test

1. Make sure your instance is disconnected from GAM
2. Check out this branch and visit the Advertising dashboard
3. Confirm you can use the static default ad units
4. Connect your instance with GAM
5. Visit the ad units configuration and confirm the units are no longer "default units" and you can edit them
6. Visit your GAM dashboard and confirm the units are created
7. Disconnect from GAM again
8. Confirm the default units are still treated as GAM items, but "Disconnected from GAM"

2022-10-25 23:56 UTC, dkoo requested changes
This works as described, but a couple of nitpicks. I'm testing with a new site connecting via service account credentials:

1. If you connect to GAM via a service account in the GAM configuration wizard, the ad units on the page don't update until you refresh the wizard page.
2. After connecting, then disconnecting GAM, the "disconnected from GAM" ad units remain but the "default" ad units come back, resulting in duplicates of the default units.

2022-10-25 23:56 UTC, dkoo commented on includes/providers/gam/class-gam-model.php
> +					/** Only sync units that doesn't yet have an ID. */
```suggestion
					/** Only sync units that don't yet have an ID. */
```

2022-10-26 21:47 UTC, miguelpeixe commented
Good catch, thank you for the review!

3da1670ebdb7ca696f342f65e8715ee459063d58 refactors how we validate the sync. It ensures the remote data exists (not archived) and preserves the original key for the ad unit map, which prevents duplicates if GAM gets disconnected.

2022-10-26 22:44 UTC, dkoo requested changes
Thank you for the revisions—the deduplication after disconnecting GAM is working well!

On this step:

> If you connect to GAM via a service account in the GAM configuration wizard, the ad units on the page don't update until you refresh the wizard page.

I'm getting a JS error and a hard UI crash.

```
TypeError: b.name is undefined
    AdUnits webpack://newspack/./assets/wizards/advertising/views/ad-units/index.js?:142
    AdUnits webpack://newspack/./assets/wizards/advertising/views/ad-units/index.js?:142
    ct https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Bt https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    os https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Ur https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Ir https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Dr https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Pr https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Nn https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    unstable_runWithPriority https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:9
    xn https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Nn https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    _n https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Er https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    enqueueSetState https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    setState https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:9
    AdvertisingWizard webpack://newspack/./assets/wizards/advertising/index.js?:59
    AdvertisingWizard webpack://newspack/./assets/wizards/advertising/index.js?:58
    promise callback*AdvertisingWizard/< webpack://newspack/./assets/wizards/advertising/index.js?:58
    updateGAMCredentials webpack://newspack/./assets/wizards/advertising/views/ad-units/service-account-connection.js?:31
    handleCredentialsFile webpack://newspack/./assets/wizards/advertising/views/ad-units/service-account-connection.js?:48
    promise callback*handleCredentialsFile webpack://newspack/./assets/wizards/advertising/views/ad-units/service-account-connection.js?:48
    ha https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    B https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    He https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    He https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    je https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Xe https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    sa https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Xe https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Xe https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    ge https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    me https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    unstable_runWithPriority https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:9
    xn https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    ua https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    pe https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Ye https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    Ke https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    qe https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    qe https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    pl https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    _reactRootContainer https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    ml https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    render https://broad-amphibian.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9
    <anonymous> webpack://newspack/./assets/wizards/advertising/index.js?:277
    js https://broad-amphibian.jurassic.ninja/wp-content/plugins/newspack-plugin/dist/billboard.js?ver=1.94.0:146
    __webpack_require__ https://broad-amphibian.jurassic.ninja/wp-content/plugins/newspack-plugin/dist/billboard.js?ver=1.94.0:423
    __webpack_exports__ https://broad-amphibian.jurassic.ninja/wp-content/plugins/newspack-plugin/dist/billboard.js?ver=1.94.0:611
    O https://broad-amphibian.jurassic.ninja/wp-content/plugins/newspack-plugin/dist/billboard.js?ver=1.94.0:462
    <anonymous> https://broad-amphibian.jurassic.ninja/wp-content/plugins/newspack-plugin/dist/billboard.js?ver=1.94.0:612
    <anonymous> https://broad-amphibian.jurassic.ninja/wp-content/plugins/newspack-plugin/dist/billboard.js?ver=1.94.0:617
react-dom.min.js:9:64017

```

2022-10-27 21:07 UTC, dkoo approved these changes
@miguelpeixe thanks for the revisions—it's working as expected now 👍

2022-10-28 13:24 UTC, merged